### ISSUE TITLE
Idenitfying Resources not Under Configuration Management Tools Control

### ISSUE THREAD

**Issue by vaibhavgupta24** [BlueJeansNetwork/inframer#2]
I have seen scenarios where the initial Infra setup (including application deployment) was carried out using the a configuration management tool, but after the setup when the Environments are handed over to Product and support team for maintenance, multiple deployments (properties/rpm) happen without getting under the configuration management tool

Its Important to identify any such resource and bring it under the control. The tool should evolve and have a way of identifying resources not under the control

**Comment by saurabh-hirani** [comment]
Sorry for the waay too late reply. That's a totally valid scenario and I guess that if post initial adoption, teams don't care enough to use the right methods to do deploys, there will be a price to be paid in terms of human errors cropping up now and then. 

But I would rather introduce at least some level of collectors even for those environments - say pull out data for the hosts in that env from vmware/aws and go about cleaning them up. If nothing is available then providing tools to add them manually to the inframer DB would incur another manual overhead. And I am sure that those who didn't care to do the foundations cleanly would be diligent in cleaning up. Someone needs to put the foot down - identify those environments - their hosts - and start fixing them.
